### ISSUE TITLE
Zalgo is broken, bis

### ISSUE THREAD

**Issue by make-42** [planetarian/BetterDiscordPlugins#10]
Zalgo is now broken again.
Doesn't write anything

**Comment by planetarian** [comment]
Seems to work fine here. Any specific case not working or just not working period?
![image](https://user-images.githubusercontent.com/1724041/82743662-ff47a600-9d33-11ea-8f2c-886ce782d71f.png)

**Comment by make-42** [comment]
I found the issue, DiscordCrypt interferes with the zalgo plugin, disabled it for now, thanks for your help!
