### ISSUE TITLE
Zalgo does not work on the latest update.

### ISSUE THREAD

**Issue by Fahrenheit** [planetarian/BetterDiscordPlugins#4]
Is anyone else experiencing this issue? It flat out doesn't work and has been doing it for a few weeks.

**Comment by orpaa** [comment]
i think i´m experienciing this too. But Zalgo doesn´t working from a few months to me, idk how to use it, i put {{some text}} and it doesn´t corrupts

**Comment by orpaa** [comment]
that from {{some text}} was a sample text. Something more, when i try putting {{0.1/1/r:some text here}} it doesn´t work too

**Comment by Bossfuratu** [comment]
Yeah, it straight up doesn't work. It's a shame, I'd like to use it.

**Comment by planetarian** [comment]
Yep, I noticed this myself recently. I'm guessing some classname changes are at fault. Will be looking into it when I get a chance.

**Comment by Bossfuratu** [comment]
> Yep, I noticed this myself recently. I'm guessing some classname changes are at fault. Will be looking into it when I get a chance.

Ah, thank you so much! Considering I just got Better Discord today, it's nice to hear. (Also, unless it hasn't been added yet, the "Settings" button doesn't work and instead collapses the panel)
![Capture](https://user-images.githubusercontent.com/43507879/59166650-d36aea80-8af9-11e9-9cc2-47f5aa6b940e.PNG)

**Comment by Obey23** [comment]
Did this get fixed? Seems it still doesn't work for me.

**Comment by Obey23** [comment]
I looked and it's something to do with the PluginUtilities?
I don't have a clue how to try fix it, but i'll attempt for now ig until the owner replies.

**Comment by planetarian** [comment]
> > Yep, I noticed this myself recently. I'm guessing some classname changes are at fault. Will be looking into it when I get a chance.
> 
> Ah, thank you so much! Considering I just got Better Discord today, it's nice to hear. (Also, unless it hasn't been added yet, the "Settings" button doesn't work and instead collapses the panel)

That's unusual. I'm guessing that there've been breaking changes in the libraries that handle the settings menu, since it used to work. I haven't looked into the recent updated zereslib and whatnot lately, so I may have some catching up to do.

**Comment by Bossfuratu** [comment]
> > > Yep, I noticed this myself recently. I'm guessing some classname changes are at fault. Will be looking into it when I get a chance.
> > 
> > 
> > Ah, thank you so much! Considering I just got Better Discord today, it's nice to hear. (Also, unless it hasn't been added yet, the "Settings" button doesn't work and instead collapses the panel)
> 
> That's unusual. I'm guessing that there've been breaking changes in the libraries that handle the settings menu, since it used to work. I haven't looked into the recent updated zereslib and whatnot lately, so I may have some catching up to do.

Ah, gotcha! I'll try to keep myself updated since I also know someone who wants to use the plugin.

**Comment by xFahrenheightx** [comment]
Sadly still broken for me. I hope it gets fixed soon. It was one of my most used plugins.

**Comment by Bossfuratu** [comment]
> Sadly still broken for me. I hope it gets fixed soon. It was one of my most used plugins.

Yeah... Been a while. On the official BetterDiscord server I went back to past messages and it appeared to work really well before it broke. Can't be that easy to fix, but it'd be a shame if the plugin were to stay broken and get abandoned.

**Comment by planetarian** [comment]
finally updated Zalgo, the problem should be fixed now. Also did a revamp on the plugin so it's using both the new ZeresLib and the new plugin format.

**Comment by Bossfuratu** [comment]
Yup, works great! Thank you!
