### ISSUE TITLE
Zalgo Works in DMs but not in Servers, Corruption Amount doesn't Work

### ISSUE THREAD

**Issue by Bossfuratu** [planetarian/BetterDiscordPlugins#7]
It's strange that it works only in one part of Discord, so I'm assuming it's a bug?

**Comment by planetarian** [comment]
discord has been hitting us with nonstop updates to the chat window lately, and they keep breaking plugins dealing with chat text and input. it's getting pretty irritating.

**Comment by Bossfuratu** [comment]
Ah, gotcha. (I also forgot to mention that the setting sliders also are broken, my bad)
![Annotation 2019-10-07 163152](https://user-images.githubusercontent.com/43507879/66346391-13af6d80-e920-11e9-9e5f-4f423b9c0342.png)

**Comment by planetarian** [comment]
The main issue is now fixed.

As for the sliders, no idea; those are generated by ZeresLibrary and my parameter use is correct according to the library documentation. I'll have to look into that. I'll open a separate issue for it.
